// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FrameStream struct {
	ID           *int    `json:"ID"`
	URL          *string `json:"URL"`
	Position     *string `json:"Position"`
	AlgModel     *int    `json:"AlgModel"`
	EncodeNeeded *int    `json:"EncodeNeeded"`
}
