// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FrameStream struct {
	ID           *int    `json:"ID"`
	URL          *string `json:"URL"`
	Position     *string `json:"Position"`
	AlgModel     *int    `json:"AlgModel"`
	EncodeNeeded *int    `json:"EncodeNeeded"`
}

type IntelligentMsg struct {
	ID            *int    `json:"ID"`
	VehicleImgURL *string `json:"VehicleImgURL"`
	VehicleLp     *string `json:"VehicleLP"`
	VehicleType   *string `json:"VehicleType"`
	VehicleColor  *string `json:"VehicleColor"`
	TaskID        *string `json:"TaskID"`
	TimeStamp     *string `json:"TimeStamp"`
}
